version: 0.2

run-as: root

env:
  parameter-store:
    DB_URL: "/road_to_devops/DB_URL"


phases:
  install:
    commands:
      - echo "Installtion Completed!!"
  pre_build:
    commands:
      - echo "Install dependency"
      - apt update 
      - apt-get install net-tools
      - curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      - apt-get install gcc make -y
      - apt-get install nodejs -y
      - npm  install pm2@latest -g 
      - echo "DB_URL=$DB_URL" > .env
      
      



artifacts:
  files:
    - echo "Upload artifact to bucket for deploy"
    - '**/*'
